package main

// -- AUTOGENERATED FILE -- (see scripts/generate_ast.py for details...)

// simple empty struct as stand-in for an abstract class.
// let me know if there's a better way (or submit a PR!).
type Expr struct{}

type BinaryExpr struct {
	Expr
	left Expr
	op Token
	right Expr
}

type Grouping struct {
	Expr
	exp Expr
}

type Literal struct {
	Expr
	val interface{}
}

type Unary struct {
	Expr
	op Token
	right Expr
}
