package main

// -- AUTOGENERATED FILE -- (see scripts/generate_ast.py for details...)
// This is a simple implementation of the Visitor pattern from OOP
type StmtVisitor interface {
	VisitPrintStmt(c *PrintStmt)
	VisitExprStmt(c *ExprStmt)
	VisitVarStmt(c *VarStmt)
}

type Stmt interface {
	accept(v StmtVisitor)
}

// PrintStmt is a simple type of AST node
type PrintStmt struct {
	exp Expr
}

// accept method stub for PrintStmt
func (c *PrintStmt) accept(v StmtVisitor) {
	v.VisitPrintStmt(c)
}

// ExprStmt is a simple type of AST node
type ExprStmt struct {
	exp Expr
}

// accept method stub for ExprStmt
func (c *ExprStmt) accept(v StmtVisitor) {
	v.VisitExprStmt(c)
}

// VarStmt is a simple type of AST node
type VarStmt struct {
	name *Token
	init Expr
}

// accept method stub for VarStmt
func (c *VarStmt) accept(v StmtVisitor) {
	v.VisitVarStmt(c)
}
